// Code generated by "go run ./internal/gen". DO NOT EDIT.

package wilayah

// datasetInfo describes the snapshot embedded in this build.
var datasetInfo = DatasetInfo{
	Version:    "2026.09.20",
	DataDate:   "2026-09-20",
	DataHash:   "52ce29195d15a284a5471f6e9a2a62236967d3878ba3574d30f632ebc6f41b28",
	SourceHash: "3c08b4ca92ab-ba8497156c5c",
	Counts: Counts{
		Provinces: 38,
		Regencies: 514,
		Districts: 7285,
		Villages:  83762,
	},
}
