// Code generated by "go run ./internal/gen". DO NOT EDIT.

package wilayah

// datasetInfo describes the snapshot embedded in this build.
var datasetInfo = DatasetInfo{
	Version:    "2026.09.20",
	DataDate:   "2026-09-20",
	DataHash:   "b5ec1f8e8605c9a719ee004cb89aeae697f83e2b929dcef8c1085aa315a3ece1",
	SourceHash: "3c08b4ca92ab-ba8497156c5c",
	Counts: Counts{
		Provinces: 38,
		Regencies: 514,
		Districts: 7285,
		Villages:  83762,
	},
}
